### ISSUE TITLE
Readme doesn't explain how to apply theme

### ISSUE THREAD

**Issue by vincentardern** [gallaux/VBEThemeColorEditor#1]
I don't believe the readme adequately explains how to apply the theme. I would update it but I'm not sure of the appropriate way to apply the theme myself...

Thanks

**Comment by gallaux** [comment]
Hey @vincentardern, honestly I thought the process to be so simple that I didn't bother writing a guide (and I'm too lazy!) 
So basically:
 - Open the app and edit the color palette to your liking. You can save and load palettes too (via the "Theme" menu).
 - Click on "Apply theme to VBE.DLL". You will then have to select the VBE6.DLL or VBE7.DLL file depending on your Excel version. The original file will be automatically backed up in its folder.
- That's it, you have replaced the original VBE color palette with a custom one. You can now adjust your settings directly in the VBA editor (Tools > Options > Editor Format).

Hope that helps!

**Comment by efriedland** [comment]
"You will then have to select the VBE6.DLL or VBE7.DLL file" - when the file location window opens, how do I know where to find the VBE.DLL file/where is it typically stored? I can't seem to track it down...

**Comment by HTPCier** [comment]
gallaux, thanks for making this available. I followed you here from superuser.com posting.
few questions I hope you continue your kindness streak and help me out a little further:  
1. Does this tool change both the Code editor window, and the Project Explorer pane or just the code window? if not, is it even possible to change the Proj Explorer Pane? 
2. You will find this funny; I'm actually stuck at "Open the app" step; and for a strange reason I now have a flashback of Jerry Maguire " you got me at hello".. sorry my ADD brain is all over the place.   but ..here goes nothing.. Open the app with what?  I'm not familiar with tools/apps that open the types of files you are using . I saw people refer to a HEX editor, but that's not for opening the tool.  I suspect I might need VS? if that is the software to use then its not happening on my end, cant use VS. BTW, I actually followed a different set of instructions and got VBE7.dll modified, and the regkeys updated but was still hoping i could explore what your tool could do.
3.  I see different folks talk about a regkey item to edit "FontFace". but in my current setting this RegKey doesn't exist.  I assume your app takes care of that, but in my case, is it a regkey I would need to add since its not there? of course Back/Forecolors are both in there.. just not FontFace

Thanks in Advance.
